name: EpicDeath
version: 1-beta
api: 3.0.0
main: FortifiePe\EpicDeath\Main
author: Taskov1ch, FortifieMix
website: https://taskovich.pro, https://vk.com/fortifiemix
load: STARTUP
description: Эффектный уход с поля боя.

permissions:
  epic.death.use:
    default: op
    description: Разрешение на эпическую смерть..