# Звуки, которые будут проигрываться при начале анимации
start:
  - mob.enderdragon.death
  # - random.totem

# Звуки, которые будут проигрываться в конце анимации (когда игрок умирает)
end:
  - random.explode

# Анимация перезарядки (анти-спам) (в секундах)
cd: 300

# Как долго игрок должен "распространяться" перед смертью? (в секундах)
duration: 10

# Настройки звука
volume: 0.1
pitch: 1
